CREATE OR ALTER VIEW v_raw_PowerUsage_Transform AS

WITH ranked_usage AS (
    SELECT 
        ESIID,
        USAGE_DATE,
        REVISION_DATE,
        USAGE_START_TIME, 
        USAGE_END_TIME, 
        USAGE_KWH,
        ESTIMATED_ACTUAL, 
        CONSUMPTION_SURPLUSGENERATION,
        ROW_NUMBER() OVER (
            PARTITION BY ESIID, USAGE_DATE, USAGE_START_TIME
            ORDER BY REVISION_DATE DESC
        ) AS rn
    FROM raw_powerusage
)

SELECT 
    SUBSTRING(ESIID, 2, LEN(ESIID) - 1) AS ESIID,
    CAST(USAGE_DATE AS DATE) AS USAGE_DATE,
    CAST(REVISION_DATE AS DATETIME) AS REVISION_DATE,
    CAST(USAGE_START_TIME AS TIME) AS USAGE_START_TIME, 
    CAST(USAGE_END_TIME AS TIME) AS USAGE_END_TIME, 
    CAST(USAGE_KWH AS FLOAT) AS USAGE_KWH,
    ESTIMATED_ACTUAL, 
    CONSUMPTION_SURPLUSGENERATION
FROM ranked_usage
WHERE rn = 1